### ISSUE TITLE
Listar tarefas

### ISSUE THREAD

**Issue by victorvp9** [jvholanda2/firstChallengeAcademy#2]
Quando solicitamos para listar as tarefas, ele pronta:
Escrita concluída com sucesso!
Salvando alterações no arquivo.
Mas nada foi escrito e nenhuma alteração foi feita, logo, não tem por que ele mostrar essas mensagens.

**Comment by joaocanuto** [comment]
Boa! Vou aplicar essa correção!

**Comment by jvholanda2** [comment]
Obrigado pela sugestão o/
