### ISSUE TITLE
Alguns problemas.

### ISSUE THREAD

**Issue by IanPacini123** [jvholanda2/firstChallengeAcademy#5]
O Xcode em si, ja faz varias reclamações que poderiam ser facilmente resolvidas para otimizar o código.
A interface eh  confusa, mas o app foi feito pra funcionar, e funciona, ent ok!
Tem alguns prints ai que parecem extras/desnecessarios tipo o "OI" esquecidokkkkkk
Mas overall funcionavel 👍.

**Comment by jvholanda2** [comment]
Obrigado pela sugestão o/
