### ISSUE TITLE
Sugestões

### ISSUE THREAD

**Issue by VanessabAlencar** [jvholanda2/firstChallengeAcademy#7]
- Inserir no menu uma opção de sair do programa;

**Comment by joaocanuto** [comment]
[https://github.com/jvholanda2/firstChallengeAcademy/commit/28f83796c84bd1b5d233dddea034c38cc3ccdd56](url)
Alterações feitas. Obrigado pela sugestão!

**Comment by jvholanda2** [comment]
Obrigado pela sugestão o/
